/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
firebolt_docs: [
  'firebolt_docs/getting-started/quick-start-guide',
  {
    type: 'autogenerated',
    dirName: 'firebolt_docs',
  },
],
  api: [
    'index',
    {
      type: 'autogenerated',
      dirName: 'api',
    },
  ],
  changelog: [
    'changelog/changelog',
    {
      type: 'autogenerated',
      dirName: 'changelog',
    },
  ],
};


module.exports = sidebarsyarn 
