docs: [
    'firebolt_docs',
    {
      type: 'category',
      label: 'Introduction',
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        'quick-start-guide',
        'hello-world',
        'how-to-use-mock-firebolt',
      ],
    },
    {
      type: 'category',
      label: 'Documentation',
      link: {
        type: 'generated-index',
        title: 'Documentation',
        keywords: ['accessibility','closed-captions','voice-guidance'],
        image: '/img/oss_logo.png',
      },
      items: [
        'firebolt_docs/accessibility',
        {
          type: 'category',
          label: 'accessibility',
          link: {
            type: 'generated-index',
            title: "Accessibility"
          },
          items: [
            'firebolt_docs/accessibility/accessibility',
            'firebolt_docs/accessibility/closed-captions',
            'firebolt_docs/accessibility/voice-guidance',
          ],
        },
        'firebolt_docs/app-lifecycle',
        {
          type: 'category',
          label: 'App Lifecycle',
          link: {
            type: 'generated-index',
            title: "App Lifecycle"
          },
          items: [
            'firebolt_docs/app-lifecycle/lifecycle-managment',
            'firebolt_docs/app-lifecycle/listening-for-events',
          ],
        },
        'styling-layout',
        'swizzling',
        'static-assets',
        'search',
        'browser-support',
        'seo',
        'using-plugins',
        'deployment',
        {
          type: 'category',
          label: 'Internationalization',
          link: {type: 'doc', id: 'i18n/introduction'},
          items: [
            {
              type: 'doc',
              id: 'i18n/tutorial',
              label: 'Tutorial',
            },
            {
              type: 'doc',
              id: 'i18n/git',
              label: 'Using Git',
            },
            {
              type: 'doc',
              id: 'i18n/crowdin',
              label: 'Using Crowdin',
            },
          ],
        },
        'guides/whats-next',
      ],
    },
    {
      type: 'category',
      label: 'Advanced Guides',
      link: {type: 'doc', id: 'advanced/index'},
      items: [
        'advanced/architecture',
        'advanced/plugins',
        'advanced/routing',
        'advanced/ssg',
        'advanced/client',
      ],
    },
    {
      type: 'category',
      label: 'Migrating from v1 to v2',
      items: [
        'migration/migration-overview',
        'migration/migration-automated',
        'migration/migration-manual',
        'migration/migration-versioned-sites',
        'migration/migration-translated-sites',
      ],
    },
  ],
  api: [
    'index',
    {
      type: 'autogenerated',
      dirName: 'api',
    },
  ],
};
