/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Firebolt",
  "tagline": "Zero Dependencies and Fast",
  "url": "https://rdkcentral.github.io",
  "baseUrl": "/firebolt-documentation/",
  "trailingSlash": true,
  "organizationName": "rdkcentral",
  "projectName": "firebolt-documentation",
  "deploymentBranch": "main",
  "scripts": [],
  "favicon": "img/favicon.png",
  "customFields": {
    "users": [
      {
        "caption": "Sky Media",
        "image": "/img/logos/1stdibs.png",
        "infoLink": "https://www.1stdibs.com/",
        "pinned": true,
        "description": "Used on Sky Glass"
      },
      {
        "caption": "Comcast",
        "image": "/img/logos/artsy.png",
        "infoLink": "http://artsy.github.io/open-source/",
        "pinned": true,
        "description": "Used on artsy.net, and the React Native iOS app, Eigen."
      }
    ]
  },
  "onBrokenLinks": "warn",
  "onBrokenMarkdownLinks": "warn",
  "onDuplicateRoutes": "throw",
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "exclude": [],
          "versions": {
            "current": {
              "label": "Next 🚧"
            }
          }
        },
        "blog": {},
        "theme": {
          "customCss": [
            "./src/css/docusaurus-1.css",
            "./src/css/prism.css",
            "./src/css/customTheme.css",
            "./src/css/custom.css"
          ]
        }
      }
    ]
  ],
  "plugins": [],
  "themeConfig": {
    "navbar": {
      "title": "Firebolt",
      "style": "primary",
      "hideOnScroll": false,
      "items": [
        {
          "type": "docSidebar",
          "position": "left",
          "sidebarId": "firebolt_docs",
          "label": "Docs"
        },
        {
          "type": "docSidebar",
          "position": "left",
          "sidebarId": "api",
          "label": "API"
        },
        {
          "type": "docsVersionDropdown",
          "position": "right",
          "dropdownItemsAfter": [
            {
              "to": "/versions",
              "label": "All versions"
            }
          ],
          "dropdownActiveClassDisabled": true,
          "dropdownItemsBefore": []
        },
        {
          "type": "doc",
          "position": "right",
          "docId": "changelog/changelog",
          "label": "Changelog"
        },
        {
          "href": "https://github.com/rdkcentral/firebolt-documentation",
          "label": "GitHub",
          "position": "right"
        }
      ]
    },
    "image": "img/relay.png",
    "footer": {
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "Get Started",
              "href": "firebolt_docs/getting-started/quick-start-guide/",
              "target": "_self"
            }
          ]
        },
        {
          "title": "Get in Touch",
          "items": [
            {
              "label": "Contact Us",
              "href": "mailto:support@rdkcentral.com",
              "target": "_self"
            },
            {
              "label": "Forum",
              "href": "https://developer.rdkcentral.com/rdk_forum/forums/",
              "target": "_self"
            }
          ]
        },
        {
          "title": "Legal",
          "items": [
            {
              "label": "Privacy",
              "href": "https://opensource.facebook.com/legal/privacy/"
            },
            {
              "label": "Terms",
              "href": "https://opensource.facebook.com/legal/terms/"
            },
            {
              "label": "Data Policy",
              "href": "https://opensource.facebook.com/legal/data-policy/"
            },
            {
              "label": "Cookie Policy",
              "href": "https://opensource.facebook.com/legal/cookie-policy/"
            }
          ]
        }
      ],
      "logo": {
        "src": "img/relay.svg"
      },
      "copyright": "Copyright © 2022 RDK Central. Built with Docusaurus.",
      "style": "light"
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "defaultLanguage": "javascript",
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "staticDirectories": [
    "static"
  ],
  "themes": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
